-- Papayoo Raffle System - Database Schema Creation
-- Version: 1.0
-- Description: Creates all required tables with proper constraints and indexes

-- Create database (run this separately if needed)
-- CREATE DATABASE papayoo_raffle_system;

-- Enable UUID extension for trace_id generation
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Table: sedes (locations)
CREATE TABLE IF NOT EXISTS sedes (
    id SERIAL PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    ciudad VARCHAR(100) NOT NULL,
    direccion VARCHAR(150),
    estado VARCHAR(20) DEFAULT 'activa' CHECK (estado IN ('activa','inactiva')),
    fecha_creacion TIMESTAMP DEFAULT NOW()
);

-- Table: clientes (customers)
CREATE TABLE IF NOT EXISTS clientes (
    id SERIAL PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    apellidos VARCHAR(100) NOT NULL,
    telefono VARCHAR(20) NOT NULL,
    correo VARCHAR(255) UNIQUE NOT NULL,
    sede_id INTEGER REFERENCES sedes(id),
    password_hash VARCHAR(255) NOT NULL,
    fecha_registro TIMESTAMP DEFAULT NOW()
);

-- Table: codigos (unique codes from EPICO)
CREATE TABLE IF NOT EXISTS codigos (
    id SERIAL PRIMARY KEY,
    codigo VARCHAR(12) UNIQUE NOT NULL,
    estado VARCHAR(20) DEFAULT 'activo' CHECK (estado IN ('activo','usado','expirado')),
    generado_por VARCHAR(50) DEFAULT 'EPICO',
    meta JSONB,
    fecha_generacion TIMESTAMP DEFAULT NOW(),
    fecha_uso TIMESTAMP,
    fecha_expiracion TIMESTAMP
);

-- Table: participaciones (raffle participations)
CREATE TABLE IF NOT EXISTS participaciones (
    id SERIAL PRIMARY KEY,
    cliente_id INTEGER REFERENCES clientes(id),
    codigo_id INTEGER REFERENCES codigos(id),
    numero_rifa VARCHAR(5) UNIQUE NOT NULL,
    fecha_asignacion TIMESTAMP DEFAULT NOW()
);

-- Table: usuarios_internos (admin users)
CREATE TABLE IF NOT EXISTS usuarios_internos (
    id SERIAL PRIMARY KEY,
    rol VARCHAR(20) DEFAULT 'admin',
    usuario VARCHAR(50) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    fecha_creacion TIMESTAMP DEFAULT NOW()
);

-- Table: configuracion_rifa (raffle configuration)
CREATE TABLE IF NOT EXISTS configuracion_rifa (
    id SERIAL PRIMARY KEY,
    estado VARCHAR(20) DEFAULT 'activa' CHECK (estado IN ('activa','pausada','cerrada')),
    numero_ganador VARCHAR(5),
    fecha_cierre TIMESTAMP,
    fecha_actualizacion TIMESTAMP DEFAULT NOW()
);

-- Table: integrations (for EPICO API keys)
CREATE TABLE IF NOT EXISTS integrations (
    id SERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    api_key_hash VARCHAR(255) NOT NULL,
    allowed_ips TEXT[],
    rate_limit INTEGER DEFAULT 1000,
    created_at TIMESTAMP DEFAULT NOW(),
    revoked_at TIMESTAMP
);

-- Table: integration_logs (audit logs)
CREATE TABLE IF NOT EXISTS integration_logs (
    id SERIAL PRIMARY KEY,
    trace_id UUID DEFAULT uuid_generate_v4(),
    endpoint VARCHAR(255),
    method VARCHAR(10),
    integration_name VARCHAR(100),
    status_code INTEGER,
    error_message TEXT,
    metadata JSONB,
    created_at TIMESTAMP DEFAULT NOW()
);

-- Create unique indexes for data integrity
CREATE UNIQUE INDEX IF NOT EXISTS idx_codigos_codigo ON codigos(codigo);
CREATE UNIQUE INDEX IF NOT EXISTS idx_participaciones_numero ON participaciones(numero_rifa);
CREATE UNIQUE INDEX IF NOT EXISTS idx_clientes_correo ON clientes(correo);
CREATE UNIQUE INDEX IF NOT EXISTS idx_usuarios_internos_usuario ON usuarios_internos(usuario);

-- Create performance indexes
CREATE INDEX IF NOT EXISTS idx_codigos_estado ON codigos(estado);
CREATE INDEX IF NOT EXISTS idx_participaciones_cliente ON participaciones(cliente_id);
CREATE INDEX IF NOT EXISTS idx_clientes_sede ON clientes(sede_id);
CREATE INDEX IF NOT EXISTS idx_integration_logs_created_at ON integration_logs(created_at);
CREATE INDEX IF NOT EXISTS idx_integration_logs_trace_id ON integration_logs(trace_id);
CREATE INDEX IF NOT EXISTS idx_codigos_fecha_generacion ON codigos(fecha_generacion);
CREATE INDEX IF NOT EXISTS idx_participaciones_fecha_asignacion ON participaciones(fecha_asignacion);

-- Add comments for documentation
COMMENT ON TABLE sedes IS 'Physical locations/stores of Papayoo';
COMMENT ON TABLE clientes IS 'Customers participating in raffles';
COMMENT ON TABLE codigos IS 'Unique codes generated by EPICO system';
COMMENT ON TABLE participaciones IS 'Raffle participation records with assigned numbers';
COMMENT ON TABLE usuarios_internos IS 'Internal admin users';
COMMENT ON TABLE configuracion_rifa IS 'Global raffle configuration and state';
COMMENT ON TABLE integrations IS 'External system integrations (EPICO)';
COMMENT ON TABLE integration_logs IS 'Audit logs for all API interactions';

-- Success message
SELECT 'Database schema created successfully!' as status;
